// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pobs.MobileNotifications.NotificationsApp;

namespace Pobs.MobileNotifications.NotificationsApp.Migrations
{
    [DbContext(typeof(MigrationDbContext))]
    partial class MigrationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Pobs.MobileNotifications.Domain.Entities.PushedNotification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Error")
                        .HasMaxLength(50);

                    b.Property<Guid?>("ExpoId");

                    b.Property<string>("Message")
                        .HasMaxLength(1000);

                    b.Property<long>("NotificationId");

                    b.Property<string>("PushToken")
                        .IsRequired()
                        .HasMaxLength(2000);

                    b.Property<long?>("RunId");

                    b.Property<DateTimeOffset>("SentAt");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.ToTable("PushedNotification");
                });

            modelBuilder.Entity("Pobs.MobileNotifications.Domain.Entities.Run", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset?>("FinishedAt");

                    b.Property<DateTimeOffset>("StartedAt");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Run");
                });

            modelBuilder.Entity("Pobs.MobileNotifications.Domain.Entities.PushedNotification", b =>
                {
                    b.HasOne("Pobs.MobileNotifications.Domain.Entities.Run")
                        .WithMany("PushedNotifications")
                        .HasForeignKey("RunId");
                });
#pragma warning restore 612, 618
        }
    }
}
